"""
scorer.py — AI Readiness Scorer Replaces the original hardcoded stub with a real multi-factor scoring model
aligned with the Claude AI Prioritization Matrix dimensions: Impact (40%): time_savings, volume_frequency, strategic_alignment Feasibility (35%): data_quality, tech_readiness, change_readiness Risk (25%): error_risk, compliance_risk Scores are derived from observable file/workflow properties and sensible
defaults. They intentionally land in the 3-4 range so they appear in the
"Good Candidate" tier - meaningful without over-claiming certainty.
The user should review and adjust scores manually in the Matrix.
"""
from __future__ import annotations from pathlib import Path
from typing import Any, Dict, Optional _BASE_IMPACT: Dict[str, Dict[str, int]] = { "excel": {"time_savings": 4, "volume_frequency": 5, "strategic_alignment": 4}, "pdf": {"time_savings": 4, "volume_frequency": 3, "strategic_alignment": 5}, "unknown": {"time_savings": 2, "volume_frequency": 2, "strategic_alignment": 2},
}
_BASE_FEASIBILITY: Dict[str, Dict[str, int]] = { "excel": {"data_quality": 4, "tech_readiness": 5, "change_readiness": 4}, "pdf": {"data_quality": 3, "tech_readiness": 4, "change_readiness": 4}, "unknown": {"data_quality": 2, "tech_readiness": 2, "change_readiness": 3},
}
_BASE_RISK: Dict[str, Dict[str, int]] = { "excel": {"error_risk": 4, "compliance_risk": 3}, "pdf": {"error_risk": 3, "compliance_risk": 3}, "unknown": {"error_risk": 2, "compliance_risk": 2},
}
_WORKFLOW_ADJ: Dict[str, Dict[str, int]] = { "clean_excel.r": {"data_quality": -1, "error_risk": +1}, "process_excel.r": {"strategic_alignment": +1, "tech_readiness": -1}, "summarize": {"time_savings": +1, "change_readiness": +1}, "questions": {"strategic_alignment": +1, "data_quality": -1, "error_risk": -1},
}
_W_IMPACT, _W_FEASIBILITY, _W_RISK = 0.40, 0.35, 0.25 def _clamp(v: int) -> int: return max(1, min(5, v)) def _size_kb(fp: Optional["str | Path"]) -> float: if not fp: return 0.0 try: return Path(fp).stat().st_size / 1024 except OSError: return 0.0 def _volume_bonus(kb: float) -> int: for i, t in enumerate([50, 200, 1000, 5000]): if kb < t: return min(i, 2) return 2 def _adj(scores: Dict[str, int], wf: str) -> Dict[str, int]: delta = _WORKFLOW_ADJ.get(wf.lower().strip(), {}) return {k: _clamp(v + delta.get(k, 0)) for k, v in scores.items()} def _avg(d: Dict[str, int]) -> float: vals = list(d.values()) return sum(vals) / len(vals) if vals else 1.0 def _tier(s: float) -> str: if s >= 4.0: return "High Priority" if s >= 3.0: return "Medium" if s >= 2.0: return "Watch List" return "Deprioritize" def _action(mode: str, wf: str, s: float) -> str: if s >= 4.0: if mode == "excel": return "Pilot R automation in first 30 days; measure time saved" return "Pilot ChatGPT PDF summarization; capture prompt + response bundle" if s >= 3.0: return "Assess data readiness and confirm process owner before piloting" return "Document process; revisit after higher-priority items are underway" def score_process( mode: str, workflow: str = "", file_path: Optional[str] = None,
) -> Dict[str, Any]: """Score a process for AI readiness. Returns dimension scores + composite.""" mode = (mode or "unknown").lower().strip() if mode not in _BASE_IMPACT: mode = "unknown" wf = (workflow or "").lower().strip() impact = _adj(dict(_BASE_IMPACT[mode]), wf) feasibility = _adj(dict(_BASE_FEASIBILITY[mode]), wf) risk = _adj(dict(_BASE_RISK[mode]), wf) kb = _size_kb(file_path) if kb > 0: impact["volume_frequency"] = _clamp(impact["volume_frequency"] + _volume_bonus(kb)) composite = round( _avg(impact) * _W_IMPACT + _avg(feasibility) * _W_FEASIBILITY + _avg(risk) * _W_RISK, 2 ) # Legacy 1-10 scale kept for backward compat with ChatGPT logger thresholds legacy_score = round(composite * 2, 1) return { # Individual dimensions (1-5) "time_savings": impact["time_savings"], "volume_frequency": impact["volume_frequency"], "strategic_alignment": impact["strategic_alignment"], "data_quality": feasibility["data_quality"], "tech_readiness": feasibility["tech_readiness"], "change_readiness": feasibility["change_readiness"], "error_risk": risk["error_risk"], "compliance_risk": risk["compliance_risk"], # Averages "impact_avg": round(_avg(impact), 2), "feasibility_avg": round(_avg(feasibility), 2), "risk_avg": round(_avg(risk), 2), "composite_score": composite, # 1-5 "priority_score": legacy_score, # 1-10 (backward compat) # Qualitative "tier": _tier(composite), "recommended_action": _action(mode, wf, composite), "mode": mode, "workflow": workflow, "file_size_kb": round(kb, 1), # Legacy string fields (ChatGPT logger uses these) "repetition": "high" if composite >= 3.5 else "medium", "structure": "high" if mode == "excel" else "medium" if composite >= 3.0 else "low", "automation_potential": ( "very high" if composite >= 4.0 else "high" if composite >= 3.0 else "medium" ), "risk": ( "low" if risk["error_risk"] >= 4 and risk["compliance_risk"] >= 4 else "medium" if risk["error_risk"] >= 3 or risk["compliance_risk"] >= 3 else "high" ), }
